config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'
  
  get 'rounds/signup'
  
  get 'rounds/:id/participants' => "rounds#participants", :as => "participants"
  
  get 'albums/:id/check' => "albums#check"
  
  root 'rounds#index'
  
  resources :albums
  
  resources :rounds
  
  resources :password_resets
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  
  resources :charges
  
  get ":id" => "users#show", :as => "profile"
end

app/models/round.rb
class Round < ActiveRecord::Base
  has_many :albums, :dependent => :destroy
  has_and_belongs_to_many :users
  
  accepts_nested_attributes_for :albums, allow_destroy: true
  accepts_nested_attributes_for :users
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:index, :signup, :participants, :show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :edit, :create, :update, :destroy]
  before_action :require_admin, only: [:new, :edit, :create, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all.order("month DESC")
    @rounds = @rounds - [@round]
  end
  
  def signup
    respond_to do |format|
      if current_user
        @round.users << current_user
        format.html { redirect_to :root }
        format.json { render :show, status: :created, location: @round }
      else
        flash[:notice] = 'Please signup or login before joining a hunt'
        format.html { redirect_to :signup }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def participants
    @users = @round.users
  end
  
  # GET /rounds/1
  # GET /rounds/1.json
  def show
    @gmaps_links = []
    @round.albums.each do |album| 
      album.places.each do |place|
        gmaps_link = place.address + ' ' + place.city + ' ' + place.state
        gmaps_link.gsub!(' ', '+')
        @gmaps_links << gmaps_link
      end
    end
  end

  # GET /rounds/new
  def new
    @round = Round.new
    3.times do
        @album = @round.albums.build
        1.times { @album.places.build }
        5.times { @album.hints.build }
        1.times { @album.build_find }
    end
  end

  # GET /rounds/1/edit
  def edit
    @round.albums.each do |album|
      unless album.find
        1.times { album.build_find }
      end
    end
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)
    
    respond_to do |format|
      if @round.save
        format.html { redirect_to @round }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to :root }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def require_admin
      if current_user.email != 'michael@unfoundsounds.com'
        redirect_to root_url, alert: 'Sorry, you don\'t have access to that page.'
      end
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      if params[:id]
        @round = Round.find(params[:id])
      else
        current_round_finished = false
        finds = []
        upcoming_round = Round.where(month: (Time.zone.now.beginning_of_month + 1.month)).first
        current_round = Round.where(month: Time.zone.now.beginning_of_month).first
        
        if current_round != nil
          current_round.albums.each do |album|
            if album.find != nil
              finds << album
            end
          end
        end
        
        if finds.count == 3
          current_round_finished = true
        end
        
        if upcoming_round != nil && current_round_finished == false
          @round = upcoming_round
          @current_round = false
        else
          @round = current_round
          @current_round = true
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:month,
      albums_attributes: [:id, :title, :band, :cover, :rdio_link, :found, :link, :link_text, :round_id, :review, :finder, :finder_photo,
        places_attributes: [:id, :teaser, :name, :link, :address, :city, :state, :description, :link_text, :album_id],
        hints_attributes: [:id, :name, :description, :photo, :thumbnail, :album_id],
        find_attributes: [:id, :user_id, :album_id, :photo]
      ])
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_album_fields.html.erb
<fieldset>
    <h3>Album</h3>
    
    <%= f.label :title, "Title" %><br />
    <%= f.text_field :title %><br />
    <%= f.label :band, "Band" %><br />
    <%= f.text_field :band %><br />
    <%= f.label :cover, "Cover" %><br />
    <%= f.file_field :cover %>
    
    <br>
    
    <%= f.fields_for :places do |builder| %>
        <%= render 'place_fields', f: builder %>
    <% end %>
    
    <br>
    <hr>
    <br>
    
    <%= f.fields_for :hints do |builder| %>
        <%= render 'hint_fields', f: builder %>
    <% end %>
    
    <%= link_to_add_fields "add hint", f, :hints %>
    
    <br>
    <hr>
    <br>
    
    <%= f.label :finder, "Finder" %><br />
    <%= f.text_field :finder %>
    <%= f.label :finder_photo, "Photo" %><br />
    <%= f.file_field :finder_photo %>
    
    <br>
    <hr>
    <br>
</fieldset>

app/views/rounds/_feature_fields.html.erb
<fieldset>
    <h3>Feature</h3>
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name %><br />
    <%= f.label :description, "Description" %><br />
    <%= f.text_area :description %><br />
    <%= f.label :photo, "Photo" %><br />
    <%= f.text_field :photo %><br />
    <%= f.label :thumbnail, "Thumbnail" %><br />
    <%= f.text_field :thumbnail %><br />
</fieldset>

app/views/rounds/_find_fields.html.erb
<fieldset>
    <h3>Finder</h3>
    <%= f.collection_select :user_id, User.all, :id, :full_name, prompt: true %><br />
    <%= f.label :photo, "Photo" %><br />
    <%= f.file_field :photo %>
    <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/rounds/_form.html.erb
<fieldset>
<%= form_for @round, :html => {:multipart => true} do |f| %>
    <% if @round.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

            <ul>
            <% @round.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <h3><%= f.label "Month" %></h3>
        <%= f.date_select :month, :discard_day => true, default: 1.month.from_now %>
    </div>

    <%= f.fields_for :albums do |builder| %>
        <%= render 'album_fields', f: builder %>
    <% end %>

    <div class="actions">
        <%= f.submit %>
    </div>
    
<% end %>
</fieldset>

app/views/rounds/_hint_fields.html.erb
<fieldset>
    <h3>Hint</h3>
    <%= f.label :description, "Description" %><br />
    <%= f.text_area :description %><br />
    <%= f.label :photo, "Photo" %><br />
    <%= f.file_field :photo %><br />
    <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/rounds/_place_fields.html.erb
<fieldset>
    <h3>Place</h3>
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name %><br />
    <%= f.label :city, "City" %><br />
    <%= f.text_field :city %><br />
    <%= f.label :link, "Link" %><br />
    <%= f.text_field :link %><br />  
    <%= f.label :link_text, "Link text" %><br />
    <%= f.text_field :link_text %><br />
    <%= f.label :description, "Description" %><br />
    <%= f.text_area :description %><br />
</fieldset>

app/views/rounds/_show.html.erb
<main class="body">
    <% if @round != nil %>
        <% if Round.where("month > ?", @round.month).order("month DESC") != [] %>
            <div class="body--prev">
                <a data-remote="true" href="/rounds/<%= Round.where("month > ?", @round.month).order("month ASC").first.id %>">
                    <%= image_tag "prev.png" %>
                </a>
            </div>
        <% end %>
        <div class="body--albums">
            <% @round.albums.each do |album| %>
                <section class="albums--album">
                    <%= link_to album_path(album), class: "album--link" do |link| %>
                        <div class="album--image">
                            <%= image_tag(album.cover) %>
                        </div>
                    <% end %>
                </section>
            <% end %>
            <% @round.albums.each_with_index do |album, index| %>
                <div class="album--content">
                    <header class="content--title">
                        <h1><%= link_to "\"#{album.title}\" by #{album.band}", album_path(album) %></h1>
                    </header>
                    <% if album.find.user != nil %>
                        <% album.places.each do |place| %>
                            <div class="content--description">
                                <h4>
                                    <em>found at <%= link_to place.name, place.link %> by 
                                    <%= link_to "#{album.find.user.first_name} #{album.find.user.last_name}", user_path(album.find.user) %>
                                    </em>
                                </h4>
                            </div>
                            <div class="content--photo">
                                <div class="photo--background" style="background-image: url(<%= album.find.photo %>)">
                                </div>
                                <div class="photo--text">
                                    <p><%= place.description %></p>
                                    <p>Visit <%= place.name %>: 
                                    <a href="https://www.google.com/maps/place/<%= @gmaps_links[index] %>" target="_blank">
                                        <%= place.address %> in <%= place.city %>
                                    </a></p>
                                </div>
                            </div>
                        <% end %>
                    <% else %>
                        <% album.places.each do |place| %>
                            <% if place.city != "" %>
                                <div class="content--description">
                                    <h4>
                                        <em>
                                            <% if @round.month != Date.today.beginning_of_month %>
                                                will be
                                            <% end %>
                                            hidden somewhere in <%= place.city %></em>
                                    </h4>
                                </div>
                            <% end %>
                            <% if Date.today.beginning_of_month == @round.month %>
                                <% album.hints.each_with_index do |hint, index| %>
                                    <div class="content--photo">
                                        <div class="photo--text">
                                            <h5>hint #<%= index + 1 %></h5>
                                            <p><%= hint.description %></p>
                                            <div class="next-prev--container">
                                                <p class="text--hints">
                                                    see more hints
                                                </p>
                                                <% if index == 0 %>
                                                    <div class="text--next first">▶</div>
                                                <% elsif index > 0 && index + 1 < album.hints.count && Date.today.day >= album.hints.count %>
                                                    <div class="text--prev">◀</div>
                                                    <div class="text--next">▶</div>
                                                <% else %>
                                                    <div class="text--prev">◀</div>
                                                <% end %>
                                            </div>
                                        </div>
                                        <div class="photo--background" style="background-image: url(<%= hint.photo %>)">
                                        </div>
                                    </div>
                                <% end %>
                            <% else %>
                                <div class="content--photo">
                                    <div class="photo--text">
                                        <a href="<%= album.link %>" target="_blank"><%= album.link_text %></a>
                                    </div>
                                    <div class="photo--background">
                                    </div>
                                </div>
                            <% end %>
                        <% end %>
                    <% end %>
                </div>
            <% end %>
        </div>
        <% if Round.where("month < ?", @round.month).order("month DESC") != [] %>
            <div class="body--next">
                <a data-remote="true" href="/rounds/<%= Round.where("month < ?", @round.month).order("month DESC").first.id %>">
                    <%= image_tag "next.png" %>
                </a>
            </div>
        <% end %>
    <% else %>
        <img src="" alt="Next vinyl treasure hunt coming soon"/>
    <% end %>
</main>
<div class="body--round">
    <% if @round != nil %>
        <h3>Vinyl Treasure Hunt, Round <%= @round.id %>: <%= @round.month.strftime("%B 1-8, %Y") %></h3>
    <% else %>
        <h3>Please wait until the first treasure hunt is scheduled.</h3>
    <% end %>
</div>

<script>
$(document).on("page:load", function(){
    if (Modernizr.mq('(min-width: 584px)')) {
        showAlbumInfo();
    }
    $(".text--prev").click(function(){
        $(this).parent().parent().parent().hide();
        $(this).parent().parent().parent().prev().css("display", "flex");
    });
    
    $(".text--next").click(function(){
        $(this).parent().parent().parent().hide();
        $(this).parent().parent().parent().next().css("display", "flex");
    });
});

$(document).ready(function(){
    if (Modernizr.mq('(min-width: 584px)')) {
        showAlbumInfo();
    }
    $(".text--prev").click(function(){
        $(this).parent().parent().parent().hide();
        $(this).parent().parent().parent().prev().css("display", "flex");
    });
    
    $(".text--next").click(function(){
        $(this).parent().parent().parent().hide();
        $(this).parent().parent().parent().next().css("display", "flex");
    });
});

$(document).on('click', '.header--logo a[data-remote=true]', function(e) {
    history.pushState({}, '', $(this).attr('href'));
});

$(document).on('click', '.header--title a[data-remote=true]', function(e) {
    history.pushState({}, '', $(this).attr('href'));
});

$(document).on('click', '.body--prev a[data-remote=true]', function(e) {
    history.pushState({}, '', $(this).attr('href'));
});

$(document).on('click', '.body--next a[data-remote=true]', function(e) {
    history.pushState({}, '', $(this).attr('href'));
});

$(window).on('popstate', function () {
    $.get(document.location.href)
});

function showAlbumInfo() {
    if (Modernizr.mq('(min-width: 584px)')) {
        $(".albums--album").on("click", toggleAlbumInfo);
    }
    
    $(window).bind("popstate", function() {
        toggleAlbumInfo();
    });
    
    var showingAlbumInfo = false;
    var roundLink;
    
    function toggleAlbumInfo(e) {
        e.preventDefault();
        if (showingAlbumInfo === false) {
            link = $(this).children(".album--link").attr('href');
            roundLink = window.location.href;
            history.pushState(null, $(this).children(".album--slug"), link);
            $(this).addClass("top");
            if ($(this).index() === 0) {
                $(".albums--album:nth-of-type(2)").addClass('move-once');
                $(".albums--album:nth-of-type(3)").addClass('move-twice');
                $(".album--content:nth-of-type(1)").fadeIn(500);
            } else if ($(this).index() === 1) {
                $(this).addClass('move-once');
                $(".albums--album:nth-of-type(3)").addClass('move-twice');
                $(".album--content:nth-of-type(2)").fadeIn(500);
            } else {
                $(".albums--album:nth-of-type(3)").addClass('move-twice');
                $(".albums--album:nth-of-type(2)").addClass('move-once');
                $(".album--content:nth-of-type(3)").fadeIn(500);
            }
            $(".body--round").on("click", toggleAlbumInfo);
            $(".body--round").css("cursor", "pointer");
            
            showingAlbumInfo = true;
        } else {
            link = $(this).children(".album--link").attr('href');
            history.pushState(null, "", roundLink);
            $(".album--content").fadeOut(500);
            $(".albums--album").removeClass("move-once");
            $(".albums--album").removeClass("move-twice");
            $(".albums--album").removeClass("top");
            $(".body--round").off("click", toggleAlbumInfo);
            $(".body--round").css("cursor", "text");
            
            showingAlbumInfo = false;
        }
    }
}
</script>

app/views/rounds/_user_fields.html.erb
<fieldset>
    <h3>Finder</h3>
    <%= f.collection_select :user_id, User.all, :id, :full_name, prompt: true %><br />
</fieldset>

app/views/rounds/edit.html.erb
<main class="body">
<%= render 'form' %>

<p><%= link_to 'Destroy',  @round,  method: :delete, data: { confirm: 'Are you sure?' } %></p>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>
</main>

app/views/rounds/index.html.erb
<% @joined = true %>
<div class="body">
    <% if @current_round == true %>
        <% found_albums = 0 %>
        <% @round.albums.each do |album| %>
            <% unless album.finder == "" || album.finder == nil %>
                <% found_albums = found_albums + 1 %>
            <% end %>
        <% end %>
        <% if found_albums == 3 %>
            <main class="body--main current-round">
                <h1>ENJOY THE FREE VINYL</h1>
                <p class="main--description">This month's vinyl treasure hunt is a wrap.<br> Please return <%= (Date.today.beginning_of_month + 1.month).strftime("%A, %B %e") %>, when the next round begins.</p>
        <% else %>
            <main class="body--main current-round">
                <h1>THE VINYL TREASURE HUNT IS ON</h1>
                <p class="main--description">
                    It started 
                        <% if Time.zone.now.beginning_of_month.day == Time.zone.today.day %>
                            today.
                        <% else %>
                            <%= Date.today.beginning_of_month.strftime("%A, %B %e") %>.
                        <% end %>
                    <br> These records are hidden in local establishments we love.
                </p>
        <% end %>
    <% else %>
        <main class="body--main upcoming-round">
            <h1>GET READY FOR THE NEXT VINYL TREASURE HUNT</h1>
            <p class="main--description">Starting <%= (Time.zone.today.beginning_of_month + 1.month).strftime("%A, %B %e") %>, these albums will be hidden in local establishments we love.</p>
    <% end %>
        <% if @current_round == true %>
            <div class="body--albums">
                <% @round.albums.each do |album| %>
                    <% unless album.finder == "" || album.finder == nil %>
                        <section class="albums--album moving-album">
                    <% else %>
                        <section class="albums--album moving-album" style="border-bottom: 10px solid #578280">
                    <% end %>
                        <div class="album--image">
                            <%= image_tag(album.cover) %>
                        </div>
                        <div class="album--info">
                            <p><%= "\"#{album.title}\" by #{album.band}" %></p>
                            <% unless album.finder == "" || album.finder == nil %>
                                <% album.places.each do |place| %>
                                    <em>found at <%= place.name %><br> by  <%= album.finder %>
                                    </em>
                                <% end %>
                            <% else %>
                                <% album.places.each do |place| %>
                                    <em>hidden in <%= place.city %></em>
                                <% end %>
                            <% end %>
                        </div>
                    </section>
                    <% unless album.finder == "" || album.finder == nil %>
                        <section class="albums--info">
                            <div class="info--container">
                                <div class="info--photo" style="background-image: url(<%= album.finder_photo %>); background-size: cover; background-position: 50% 50%;">
                                </div>
                                <div class="info--text found current">
                                    <% album.places.each do |place| %>
                                        <h4>found at <%= place.name %></h4>
                                        <p><%= place.description %></p>
                                        <p><a href="<%= place.link %>" target="_blank"><em><%= place.link_text %></em></a></p>
                                    <% end %>
                                </div>
                            </div>
                        </section>
                    <% else %>
                        <section class="albums--info">
                            <% album.hints.each_with_index do |hint, index| %>
                                <% if index + 1 <= Time.zone.today.day %>
                                    <div class="info-container">
                                        <div class="info--photo" style="background-image: url(<%= hint.photo %>); background-size: cover; background-position: 50% 50%;">
                                            <% unless album.hints.size == 1 %>
                                                <% unless Time.zone.today.day == 1 %>
                                                    <div class="info--button">
                                                        <% unless index == 0 %>
                                                            <div class="button--prev">
                                                                ◀
                                                            </div>
                                                        <% end %>
                                                        <div class="button--hints">
                                                            see more
                                                        </div>
                                                        <% unless index == album.hints.size - 1 %>
                                                            <% if index + 2 <= Time.zone.today.day %>
                                                                <div class="button--next">
                                                                    ▶
                                                                </div>
                                                            <% end %>
                                                        <% end %>
                                                    </div>
                                                <% end %>
                                            <% end %>
                                        </div>
                                        <%= form_tag("/albums/#{album.slug}/check", method: "get", class: "info--form") do %>
                                            <h3>Take a guess</h3>
                                            <%= image_tag("close-expand.png", class: "form--close") %>
                                            <%= label_tag(:place, "Place name") %>
                                            <%= text_field_tag(:place) %>
                                            <%= label_tag(:email, "Your email address") %>
                                            <%= text_field_tag(:email) %>
                                            <p>(We'll email you if you provide an alternate place spelling.)</p>
                                            <%= submit_tag("Submit") %>
                                        <% end %>
                                        <% if index + 1 == Time.zone.today.day || index == album.hints.size - 1 %>
                                            <div class="info--text show">
                                        <% else %>
                                            <div class="info--text">
                                        <% end %>
                                            <h4>hint no. <%= index + 1 %></h4>
                                            <p><%= hint.description %></p>
                                            <% if index + 1 == Time.zone.today.day %>
                                                <p><em>Check back tomorrow for another hint, if the album remains unfound.</em></p>
                                            <% end %>
                                            <div class="hidden">
                                                <p>Know where it's hidden?</p>
                                                <div class="info--check">
                                                    Take a guess
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <% end %>
                            <% end %>
                        </section>
                    <% end %>
                <% end %>
            </div>
        <% else %>
            <div class="body--albums">
                <% @round.albums.each do |album| %>
                    <section class="albums--album">
                        <div class="album--image">
                            <%= image_tag(album.cover) %>
                        </div>
                        <div class="album--info">
                            <p><%= "\"#{album.title}\" by #{album.band}" %></p>
                            <% album.places.each do |place| %>
                                <em>hidden in <%= place.city %></em>
                            <% end %>
                        </div>
                        <div class="album--signup">
                            <h1>Please return <%= (Date.today.beginning_of_month + 1.month).strftime("%A, %B %e") %> for hints.</h1>
                        </div>
                    </section>
                <% end %>
            </div>
        <% end %>
    </main>
    <div class="body--found-container">
        <header class="body--found-header">
            <h1>PAST ROUNDS</h1>
        </header>
        <% @rounds.each_with_index do |round, index| %>
            <% if round != nil %>
                <div class="body--albums">
                    <% round.albums.each do |album| %>
                        <section class="albums--album moving-album">
                            <div class="album--image">
                                <%= image_tag(album.cover) %>
                            </div>
                            <div class="album--info">
                                <p><%= "\"#{album.title}\" by #{album.band}" %></p>
                                <% album.places.each do |place| %>
                                    <em>found at <%= place.name %><br> by  <%= album.finder %>
                                    </em>
                                <% end %>
                            </div>
                        </section>
                        <section class="albums--info">
                            <div class="info--container">
                                <div class="info--photo" style="background-image: url(<%= album.finder_photo %>); background-size: cover; background-position: 50% 50%;">
                                </div>
                                <div class="info--text found">
                                    <% album.places.each do |place| %>
                                        <h4>found at <%= place.name %></h4>
                                        <p><%= place.description %></p>
                                        <p><a href="<%= place.link %>" target="_blank"><em><%= place.link_text %></em></a></p>
                                    <% end %>
                                </div>
                            </div>
                        </section>
                    <% end %>
                </div>
            <% else %>
                <img src="" alt="Next vinyl treasure hunt coming soon"/>
            <% end %>
        <% end %>
    </div>
</div>

app/views/rounds/participants.html.erb
<h1><% @round.month %></h1>
<% @users.each do |user| %>
<ul>
    <li>
        <p><%= user.first_name %> <%= user.last_name %></p>
        <p><%= user.email %></p>
        <p><%= user.city %></p>
    </li>
</ul>
<% end %>

app/views/rounds/show.html.erb
<div class="body">
    <main class="body--main">
        <% if @current_round == true %>
            <div class="body--albums current_round">
        <% else %>
            <div class="body--albums upcoming_round">
        <% end %>
            <% @round.albums.each do |album| %>
                <section class="albums--album">
                    <%= link_to album_path(album), class: "album--link" do |link| %>
                        <div class="album--image">
                            <%= image_tag(album.cover) %>
                        </div>
                    <% end %>
                </section>
            <% end %>
        </div>
    </main>
</div>

app/views/rounds/show.js.erb
setTimeout(function(){
    $('.wrapper').html('<%= j render("show") %>');
}, 500)