config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'
  
  get 'rounds/signup'
  
  get 'rounds/:id/participants' => "rounds#participants", :as => "participants"
  
  get 'albums/:id/check' => "albums#check"
  
  root 'rounds#index'
  
  resources :albums
  
  resources :rounds
  
  resources :password_resets
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  
  resources :charges
  
  get ":id" => "users#show", :as => "profile"
end

app/models/album.rb
class Album < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  belongs_to :round
  has_one :find, :foreign_key => :album_id
  
  has_many :places, :dependent => :destroy
  has_many :hints, :dependent => :destroy
  
  accepts_nested_attributes_for :find
  accepts_nested_attributes_for :places, allow_destroy: true
  accepts_nested_attributes_for :hints, allow_destroy: true
  
  mount_uploader :cover, CoverUploader
  mount_uploader :finder_photo, FinderUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:check, :show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end
  
  def check
    answer = false
    
    @album.places.each do |place|
      if place.name == params[:place]
        answer = true
      end
    end
    
    if answer == true
      CorrectMailer.correct(params[:place], "\"#{@album.title}\"", params[:email]).deliver_now
      redirect_to :root, alert: "You\'re right! Get to #{params[:place]} fast, and pick up that great album by #{@album.band}."
    else
      CheckMailer.check(params[:place], "\"#{@album.title}\"", params[:email]).deliver_now
      redirect_to :root, alert: "Sorry, that's not what we have. We'll double-check to see if you provided an alternate spelling, and email you if so."
    end
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :band, :cover, :rdio_link, :found)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :band %><br>
    <%= f.text_field :band %>
  </div>
  <div class="field">
    <%= f.label :cover %><br>
    <%= f.text_field :cover %>
  </div>
  <div class="field">
    <%= f.label :rdio_link %><br>
    <%= f.text_field :rdio_link %>
  </div>
  <div class="field">
    <%= f.label :found %><br>
    <%= f.check_box :found %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Albums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Band</th>
      <th>Cover</th>
      <th>Rdio link</th>
      <th>Found</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= album.band %></td>
        <td><%= album.cover %></td>
        <td><%= album.rdio_link %></td>
        <td><%= album.found %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<% @album.places.each do |place| %>
    <% @gmaps_link = place.address + ' ' + place.city + ' ' + place.state %>
    <% @gmaps_link.gsub!(' ', '+') %>
<% end %>
<div class="body">
    <main class="body--main">
        <div class="body--albums">
            <section class="albums--album">
                <div class="album--image">
                    <%= image_tag(@album.cover) %>
                </div>
            </section>
            <div class="album--content"><p>
                <header class="content--title">
                    <h1><%= "\"#{@album.title}\" by #{@album.band}" %></h1>
                </header>
                <% if @album.find != nil %>
                    <% @album.places.each do |place| %>
                        <div class="content--description">
                            <h4>
                                <em>found at <%= link_to place.name, place.link %> by 
                                <%= link_to "#{@album.find.user.first_name} #{@album.find.user.last_name}", user_path(@album.find.user) %>
                                </em>
                            </h4>
                        </div>
                        <div class="content--photo">
                            <div class="photo--background" style="background-image: url(<%= @album.find.photo %>)">
                            </div>
                            <div class="photo--text">
                                <p><%= place.description %></p>
                                <p>Visit <%= place.name %>: 
                                <a href="https://www.google.com/maps/place/<%= @gmaps_link %>" target="_blank">
                                    <%= place.address %> in <%= place.city %>
                                </a></p>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <% @album.places.each do |place| %>
                        <% if place.city != "" %>
                            <div class="content--description">
                                <h4>
                                    <em>
                                        <% if @album.round.month != Date.today.beginning_of_month %>
                                            will be
                                        <% end %>
                                        hidden somewhere in <%= place.city %></em>
                                </h4>
                            </div>
                        <% end %>
                        <% if Date.today.beginning_of_month == @album.round.month %>
                            <% @album.hints.each_with_index do |hint, index| %>
                                <div class="content--photo">
                                    <div class="photo--text">
                                        <h5>hint #<%= index + 1 %></h5>
                                        <p><%= hint.description %></p>
                                        <div class="next-prev--container">
                                            <p class="text--hints">
                                                see more hints
                                            </p>
                                            <% if index == 0 %>
                                                <div class="text--next first">▶</div>
                                            <% elsif index > 0 && index + 1 < @album.hints.count && Date.today.day >= @album.hints.count %>
                                                <div class="text--prev">◀</div>
                                                <div class="text--next">▶</div>
                                            <% else %>
                                                <div class="text--prev">◀</div>
                                            <% end %>
                                        </div>
                                    </div>
                                    <div class="photo--background" style="background-image: url(<%= hint.photo %>)">
                                    </div>
                                </div>
                            <% end %>
                        <% else %>
                            <div class="content--photo">
                                <div class="photo--text">
                                    <a href="<%= @album.link %>" target="_blank"><%= @album.link_text %></a>
                                </div>
                                <div class="photo--background">
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </main>
</div>